services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-canvas_db}
      POSTGRES_USER: ${DB_USER:-canvas_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-canvas_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-canvas_user} -d ${DB_NAME:-canvas_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-canvas_user}:${DB_PASSWORD:-canvas_pass}@db:5432/${DB_NAME:-canvas_db}
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    volumes:
      - ./static:/app/static

volumes:
  postgres_data:
  redis_data: