name: Frontend CI (optional)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-ui:
    if: ${{ hashFiles('ui/package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - name: Install & build
        working-directory: ui
        run: |
          npm ci
          npm run build